language: node_js
node_js:
  - "lts/*"
before_install:
  - sudo apt-get install libblas-dev
install:
  - npm install
env:
  global:
    - CXX=g++-4.9
    - CC_TEST_REPORTER_ID=7fead1a8381deb5adf50d0bd753387a4d970472ce301b6ade44f5f8c43d66988
before_script:
  - npm install -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
